columnSuffix: null
handle: heroHeading
instructions: 'Main hero title ("What Do You Want To Do?")'
name: "Hero Heading"
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
