columnSuffix: null
handle: plainText
instructions: "single line, like a title or button label"
name: "Plain Text"
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
