columnSuffix: null
handle: ratingReviews
instructions: null
name: "Rating & Reviews"
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    - __assoc__:
        - - uid
          - 0df6553f-f45d-4850-b322-93e5928dda9c # Reviews
        - - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
