columnSuffix: null
handle: socialLinks
instructions: null
name: "Social Links"
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    - __assoc__:
        - - uid
          - 1e728745-97d0-4855-a067-8c8d1eb5f16d # Social Link
        - - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
