columnSuffix: null
handle: thingsToDoNearby
instructions: null
name: 'Things to Do Nearby'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Things1
            -
              - handle
              - things1
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Things2
            -
              - handle
              - things2
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Things3
            -
              - handle
              - things3
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - rowId
          - 55043b43-a1c5-4468-97e9-f872ad412001
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
