fieldLayouts:
  201bfa39-1f33-43e5-a893-609a090833ae:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-29T09:53:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7d446b03-5b7b-42d7-a565-2a09111b0985 # Header logo
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81fcf7c5-cd62-47d4-b511-f11ff7849c1c
            userCondition: null
            warning: null
            width: 100
        name: 'Header information'
        uid: e47a026f-d71d-449f-8672-9f94cb723d83
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-29T09:53:37+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a13faae7-0d7e-453f-810f-bbeccd14ff63 # header naviagation
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b428eed-0f9b-4fc2-8753-707e13daf0fe
            userCondition: null
            warning: null
            width: 100
        name: 'header Navigation'
        uid: 839635bf-a030-4ea1-afe4-b01a31a54576
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-31T10:05:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 986971ec-c1af-4f0e-a434-17aba27369f2 # Address
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abc48acc-9899-4562-928f-8571e71f6fcb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-07-31T10:12:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 09119c81-3ac3-4a45-956c-8754ee06c4cc # Phone Number
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 638775c8-9622-4340-9024-2759f7f31fe1
            userCondition: null
            warning: null
            width: 100
        name: 'Address tab'
        uid: c884e6b6-b8c6-4dc6-9cd4-608125b81ec4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-31T10:05:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 255b6925-5561-4791-ab95-9ab8748927b9 # Social Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fac61805-adfd-41a6-aad9-23dd1b417727
            userCondition: null
            warning: null
            width: 100
        name: 'social links'
        uid: 61664e71-fef5-4006-9733-8188ba546764
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-31T10:14:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1d0a82b7-77d8-4b65-9ab6-f25aa5029ab1 # Featured Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5930900-7aaf-4e23-8e47-e0d199d86694
            userCondition: null
            warning: null
            width: 100
        name: 'header sidebar image tab'
        uid: b4664e9e-c34f-4463-a069-8a3af3dc87f5
        userCondition: null
    thumbFieldKey: null
handle: header
name: Header
sortOrder: 1
