currLabel: 'Plugin Store'
customIcon: null
enabled: true
handle: plugin-store
icon: plug
layout: 005e810e-1762-4053-8112-618d4f4208dc # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 7
type: craft
url: plugin-store
