defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5ca5ba24-4b6a-4724-8080-c4d5bc6e3954 # Privacy policy
handle: privacyPolicy
maxAuthors: 1
minAuthors: 1
name: 'Privacy policy'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  bdeb5182-f6c3-4403-9323-0ab9afff1795: # DO San Diego
    enabledByDefault: true
    hasUrls: true
    template: pages/privacy-policy.twig
    uriFormat: privacy-policy
type: single
