name: Deploy on Production do-san-diego App!

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            cd public_html/2026/cms/do-san-diego/
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php craft up --interactive=0
            php craft clear-caches/all 


            